# **Array Creation**

**Problem - 1: Array Creation: **

In [ ]:
import numpy as np
a=np.zeros((2,2),dtype="int32")
print(a)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
b=np.ones((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
c=np.full((4,2),"fill_value")
print(c)

[['fill_value' 'fill_value']
 ['fill_value' 'fill_value']
 ['fill_value' 'fill_value']
 ['fill_value' 'fill_value']]


In [ ]:
import numpy as np
d=np.zeros_like(a)
print(d)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
e=np.ones_like(b)
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
new_list=[1,2,3,4]
print(new_list)
new_array=np.array(new_list)
print(new_array)

[1, 2, 3, 4]
[1 2 3 4]


**Problem - 2: Array Manipulation**

In [ ]:
import numpy as np
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
b=np.arange(0,9)
print(b)

c=b.reshape((3,3))
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
d=np.eye(3)
print(d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


72

In [ ]:
import numpy as np
e=np.random.rand(30)
print(e)
f=e.mean()
print(f)
np.size(e)

[0.09368919 0.46794086 0.79365857 0.54128626 0.62894166 0.52750032
 0.23649062 0.75816383 0.25105315 0.24170538 0.56805352 0.45554149
 0.05125829 0.272927   0.85591116 0.28006056 0.31867067 0.17063925
 0.05543358 0.17000691 0.09004887 0.82448796 0.30750478 0.24432846
 0.21249286 0.87384191 0.50490214 0.51601308 0.20615033 0.42939098]
0.3982697881242514


30

In [ ]:
import numpy as np
f=np.random.rand(10,10)
min=np.min(f)
max=np.max(f)
print(min)
print(max)

0.006149340999413888
0.9723639630019355


In [ ]:
import numpy as np
g=np.zeros((1,10))
print(g)

g[:,4]=1
print(g)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.array([1,2,0,0,4,0])
rev_arr=arr[::-1]
print(rev_arr)

[0 4 0 0 2 1]


In [ ]:
import numpy as np
ones=np.ones((4,4))
print(ones)

zeros=np.zeros((2,2))
print(zeros)

ones[1:-1,1:-1]=zeros
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
a=np.full((8,8),1)
a[1::2, ::2]=0
a[::2, 1::2]=0
print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**Problem - 3: Array Operation**

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(w)

[11 12]


In [ ]:
import numpy as np

print(x+y)


[[ 6  8]
 [10 13]]


In [ ]:
import numpy as np
print(x-y)

[[-4 -4]
 [-4 -3]]


In [ ]:
import numpy as np
print(x*2)

[[ 2  4]
 [ 6 10]]


In [ ]:
import numpy as np
print(x**2)

[[ 1  4]
 [ 9 25]]


In [ ]:
vw=np.dot(v,w)
print(vw)
xv=np.dot(x,v)
print(xv)
xy=np.dot(x,y)
print(xy)

219
[29 77]
[[19 22]
 [50 58]]


In [ ]:
import numpy as np
h=np.hstack([x,y])
print(h)
z=np.vstack([v,w])
print(z)

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
import numpy as np
c=np.concatenate([x,v])
print(c)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

*While concatenating the input arrays must have same number of dimensions. But in the source code array 'x' has 2 dimensions and the array 'v' has 1 dimension due to which decoder raised the "valueError" error.*

Problem - 4: Matrix Operation

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [ ]:
import numpy as np
Ainv=np.linalg.inv(A)
print(Ainv)

prove=np.dot(A,Ainv)
print(prove)

[[-2.    1.  ]
 [ 1.75 -0.75]]
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
ab=np.dot(A,B)
print(ab)
ba=np.dot(B,A)
print(ba)
print("Hence, AB!=BA")

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Hence, AB!=BA


In [ ]:
import numpy as np
ab=np.matmul(A,B)
ab_transpose=np.transpose(ab)
print(ab_transpose)

a_transpose=np.transpose(A)
b_transpose=np.transpose(B)
ba=np.dot(b_transpose,a_transpose)
print(ba)

print("Hencce (AB)_tranpose == B_transpose . A_transpose")


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
Hencce (AB)_tranpose == B_transpose . A_transpose


In [ ]:
import numpy as np
print("2x-3y+z=-1\nx-y+2z=-3\n3x+y-z=9\n ")
print("In Matrix form:\n")

A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
print(f"A={A}\nB={B}\n")
A_det=np.linalg.det(A)
print(f"A_det:{A_det}\n")
A_inv=np.linalg.inv(A)
print(f"A_inverse:{A_inv}\n")
X=np.dot(A_inv,B)
print(f"A'.B={X}")


2x-3y+z=-1
x-y+2z=-3
3x+y-z=9
 
In Matrix form:

A=[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B=[-1 -3  9]

A_det:-19.000000000000004

A_inverse:[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

A'.B=[ 2.  1. -2.]


# **Experiment: **

In [ ]:
import time
import numpy as np

# 1. Element-wise Addition

# Using Python lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")

# Using NumPy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array_add = array1 + array2
end_time = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using Python lists: 0.16325759887695312 seconds
Time taken for element-wise addition using NumPy arrays: 0.0040302276611328125 seconds


In [ ]:
import time
import numpy as np

# 2. Element-wise Multiplication

# Using Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")

# Using NumPy arrays
start_time = time.time()
result_array_mul = array1 * array2
end_time = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")

Time taken for element-wise multiplication using Python lists: 0.3307974338531494 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.006510019302368164 seconds


In [ ]:
import time
import numpy as np

# 3. Dot Product

# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.3119204044342041 seconds
Time taken for dot product using NumPy arrays: 0.002804279327392578 seconds


In [230]:
import time
import numpy as np

# 4. Matrix Multiplication

# Using Python lists
matrix1 = [[i for i in range(1000)] for _ in range(1000)]
matrix2 = [[i for i in range(1000)] for _ in range(1000)]

start_time = time.time()
result_matrix_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")

# Using NumPy arrays
matrix1_np = np.arange(1000000).reshape(1000, 1000)
matrix2_np = np.arange(1000000).reshape(1000, 1000)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 253.15927624702454 seconds
Time taken for matrix multiplication using NumPy arrays: 1.2355778217315674 seconds
